[Config1]
num_points = 10000
base_amplitude = 5.0
base_frequency = 0.05
base_noise_scale = 1
base_noise_amplitude = 1
num_trend_events = 0
trend_parameters = [0.01, 0.2]
num_cosine_events = 0
cosine_frequency_params = [0.01, 0.2]
cosine_amplitude_params = [2.0, 8]
num_increased_noise_events = 0
increased_noise_params = [0.8, 2]
number_of_features = 0
test_size = 0.2
hidden_size_history = [512, 128, 32]
learning_rate_history = 0.0001
learning_rate_exog = 0.0001
hidden_size_exog = [16, 512, 256, 128, 32]
hidden_size_exog_hi = 16
num_epochs = 200
batch_size = 200
quantiles = [0.01, 0.5, 0.99]
save_path = "../Results/Synthetic/"
save_history_name = "History"
save_exog_name = "Exogenous0"
descriptor = "AdditideBaseNoise1"
noise_type = "additive"

[Config2]
num_points = 10000
base_amplitude = 5.0
base_frequency = 0.1
base_noise_scale = 1
base_noise_amplitude = 1
num_trend_events = 0
trend_parameters = [0.01, 0.2]
num_cosine_events = 0
cosine_frequency_params = [0.01, 0.2]
cosine_amplitude_params = [2.0, 8]
num_increased_noise_events = 0
increased_noise_params = [0.8, 2]
number_of_features = 0
test_size = 0.2
hidden_size_history = [512, 128, 32]
learning_rate_history = 0.0001
learning_rate_exog = 0.0001
hidden_size_exog = [16, 512, 256, 128, 32]
hidden_size_exog_hi = 16
num_epochs = 200
batch_size = 200
quantiles = [0.01, 0.5, 0.99]
save_path = "../Results/Synthetic/"
save_history_name = "History"
save_exog_name = "Exogenous0"
descriptor = "AdditideDoubleNoise1"
noise_type = "additive"